export const config = {
  baseUrl: process.env.BASE_URL || "",
  databaseUrl: process.env.DATABASE_URL || "",
  databaseCert: process.env.DATABASE_CERT || "",
  discordApiUrl: process.env.DISCORD_API_URL || "",
  discordBotToken: process.env.DISCORD_BOT_TOKEN || "",
  discordClientId: process.env.DISCORD_CLIENT_ID || "",
  discordClientSecret: process.env.DISCORD_CLIENT_SECRET || "",
  discordState: process.env.DISCORD_STATE || "",
  env: process.env.NODE_ENV || "dev",
  doSpacesBucketName: process.env.DO_SPACES_BUCKET_NAME || "",
  doSpacesEndpoint: process.env.DO_SPACES_ENDPOINT || "",
  doSpacesAccessId: process.env.DO_SPACES_ACCESS_ID || "",
  doSpacesSecretKey: process.env.DO_SPACES_SECRET_KEY || "",
};
